version: '3.8'

services:
  nginx:
    image: nginx:1.24
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www:/var/www
      - /etc/ssl/ssl:/etc/ssl/ssl
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php7.4
      - php8.1
    networks:
      dnmp:
        ipv4_address: 172.18.0.10

  php7.4:
    image: php:7.4-fpm
    container_name: php7.4
    restart: always
    volumes:
      - /var/www:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      dnmp:
        ipv4_address: 172.18.0.30

  php8.1:
    image: php:8.1-fpm
    container_name: php8.1
    restart: always
    volumes:
      - /var/www:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      dnmp:
        ipv4_address: 172.18.0.40

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lbdj147369
    networks:
      dnmp:
        ipv4_address: 172.18.0.20

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /data:/data
    networks:
      dnmp:
        ipv4_address: 172.18.0.50

networks:
  dnmp:
    ipam:
      config:
        - subnet: 172.18.0.0/16
